//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRegistry.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateDistMapping
    {
        public int Id { get; set; }
        public int StateId { get; set; }
        public int DistId { get; set; }
    
        public virtual District District { get; set; }
        public virtual State State { get; set; }
    }
}
